<?php

// Exit if accessed directly
if ( !defined('ABSPATH')) exit;

/**
 *
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */
require ( get_template_directory() . '/core/includes/functions.php' );
require ( get_template_directory() . '/core/includes/theme-options.php' );
require ( get_template_directory() . '/core/includes/post-custom-meta.php' );
require ( get_template_directory() . '/core/includes/tha-theme-hooks.php' );
require ( get_template_directory() . '/core/includes/hooks.php' );
require ( get_template_directory() . '/core/includes/version.php' );

/* Use custom.js for generic site functionality */
add_action( 'wp_enqueue_scripts', 'rs_custom_js' );
function rs_custom_js() {
	wp_enqueue_script( 'cutsomjs', get_stylesheet_directory_uri() . '/core/js/custom.js', array( 'jquery' ), false, false);
}

/* get rid of space after read more */

function excerpt_ellipse($text) {
 
   return str_replace('<p><!-- end of .read-more --></p>', '', $text);
   //return $text . 'blahhh'; 
}

add_filter('the_excerpt', 'excerpt_ellipse');

?>
